// ui_ext.h — auto-generated by ir2eez (do not edit)
// Rich-widget structure constants: charts/tables are bare LVGL objects;
// call the lv_chart_*/lv_table_* APIs from firmware init using these values.
#pragma once


// chart chart_bus — line, 120 points, range 0..400, 2 series
#define CHART_BUS_POINTS 120
#define CHART_BUS_MIN 0
#define CHART_BUS_MAX 400
#define CHART_BUS_SERIES_0_NAME "Ibus"   // color #5EE6C4, width 2
#define CHART_BUS_SERIES_1_NAME "Limit"   // color #F2B84B, width 1

// table table_events — 3 cols x 5 rows
#define TABLE_EVENTS_COLS 3
#define TABLE_EVENTS_ROWS 5
static const char *const TABLE_EVENTS_HEADER[] = { "Time", "Code", "Message" };
#define TABLE_EVENTS_HEADER_LEN 3
